import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { createSupabaseServerClient } from "./lib/supabase/server-client";
import Footer from "./components/Footer/footer";
import Navbar from "./components/Navbar/Navbar";

const roboto = Open_Sans({
  weight: '400',
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "Avant signature builds",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <AuthProvider initialUser={user}>
           <Navbar />
           <main>
            {children}
            <Footer />
           </main>
        </AuthProvider>
      </body>
    </html>
  );
}
